name: Convert the Matter Data model to SDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=Release
          -S ${{ github.workspace }}
      - name: Build
        # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release
      - name: Pull Matter files
        run: | 
          git clone --depth=1 https://github.com/project-chip/connectedhomeip.git ${{ github.workspace }}/matter
          rm ${{ github.workspace }}/matter/data_model/master/clusters/cluster_ids.json
          mkdir ${{ github.workspace }}/converted/
      - name: Convert Matter files for Matter 1.3
        run: |
          mkdir ${{ github.workspace }}/converted/1.3/
          folder_path="${{ github.workspace }}/matter/data_model/1.3/device_types"
          for file in "$folder_path"/*; do
            if [[ -f "$file" && "${file##*.}" != "json" ]]; then
              echo "Processing $file"
              ${{ steps.strings.outputs.build-output-dir }}/sdf_matter_converter --matter-to-sdf -device-xml "$file" -cluster-xml "${{ github.workspace }}/matter/data_model/1.3/clusters" -o "${{ github.workspace }}/converted/1.3/$(basename "$file" | cut -f 1 -d '.').json"
            fi
          done
      - name: Convert Matter files for Matter 1.4
        run: |
          mkdir ${{ github.workspace }}/converted/1.4/
          folder_path="${{ github.workspace }}/matter/data_model/1.4/device_types"
          for file in "$folder_path"/*; do
            if [[ -f "$file" && "${file##*.}" != "json" ]]; then
              echo "Processing $file"
              ${{ steps.strings.outputs.build-output-dir }}/sdf_matter_converter --matter-to-sdf -device-xml "$file" -cluster-xml "${{ github.workspace }}/matter/data_model/1.4/clusters" -o "${{ github.workspace }}/converted/1.4/$(basename "$file" | cut -f 1 -d '.').json"
            fi
          done
      - name: Convert Matter files for Master
        run: |
          mkdir ${{ github.workspace }}/converted/master/
          folder_path="${{ github.workspace }}/matter/data_model/master/device_types"
          for file in "$folder_path"/*; do
            if [[ -f "$file" && "${file##*.}" != "json" ]]; then
              echo "Processing $file"
              ${{ steps.strings.outputs.build-output-dir }}/sdf_matter_converter --matter-to-sdf -device-xml "$file" -cluster-xml "${{ github.workspace }}/matter/data_model/master/clusters" -o "${{ github.workspace }}/converted/master/$(basename "$file" | cut -f 1 -d '.').json"
            fi
          done
      - uses: actions/upload-artifact@v4
        with:
          name: Converted Matter files
          path: ${{ github.workspace }}/converted/*.json
